version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Build successful"

artifacts:
  files:
    - '**/*'
